replicaCount: 1

image:
  repository: 407291110113.dkr.ecr.us-east-1.amazonaws.com/my-devops-app
  pullPolicy: IfNotPresent
  tag: "v34"

imagePullSecrets:
  - name: ecr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}